import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Clean up old caches and claim clients immediately
cleanupOutdatedCaches();
self.skipWaiting();
clientsClaim();

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// ------------------------------------
// Runtime Caching Strategies
// ------------------------------------

// 1. API Requests (Stale-While-Revalidate)
// Serves from cache for speed, updates in background for freshness.
registerRoute(
    ({ url }) => url.pathname.startsWith('/api'),
    new StaleWhileRevalidate({
        cacheName: 'api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 5 * 60, // 5 minutes
            }),
        ],
    })
);

// 2. Images (Cache First)
// Serve from cache if available, otherwise fetch and cache.
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'image-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// ------------------------------------
// Offline Fallback
// ------------------------------------
// If navigation fails (offline), serve offline.html
const networkOnly = new NetworkOnly();
const navigationHandler = async (params) => {
    try {
        return await networkOnly.handle(params);
    } catch (error) {
        return caches.match('/offline.html');
    }
};

registerRoute(new NavigationRoute(navigationHandler));

// ------------------------------------
// Push Notifications
// ------------------------------------
self.addEventListener('push', (event) => {
    const data = event.data ? event.data.json() : {};
    const title = data.title || 'Urban Harvest Hub';
    const options = {
        body: data.body || 'New updates available!',
        icon: '/pwa-192x192.png',
        badge: '/mask-icon.svg',
        data: { url: data.url || '/' }
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            if (clientList.length > 0) {
                let client = clientList[0];
                for (let i = 0; i < clientList.length; i++) {
                    if (clientList[i].focused) {
                        client = clientList[i];
                    }
                }
                return client.focus();
            }
            return clients.openWindow(event.notification.data.url);
        })
    );
});
